<a href="https://colab.research.google.com/github/santiagovillamizarjaimes-collab/Tareas-Python-Erick/blob/main/semana10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Escritura de archivos desde Python**

In [29]:
# Crear y escribir una rchivo de texto
with open("archivo.txt", "w") as f:
  f.write("Hola, este es un archivo de texto. \n")
  f.write("Segunda linea. \n")

Con el argumento "w" se crea el archivo si no existe. También sobreescribe el archivo si ya existe, borrando todo su contenido previo.

Con archivos.txt

In [30]:
with open("archivo.txt", "r") as f:
  print(f.read())

Hola, este es un archivo de texto.
Segunda linea.

In [15]:
from google.colab import files
files.download("archivo.txt")

In [33]:
# Abrir en modo append para editar un archivo ya existente (con el argumento a)
with open("archivo.txt", "a") as f:
  f.write("\nEsta es una nueva linea añadida")

In [34]:
with open("archivo.txt", "r") as f:
  print(f.read())

Hola, este es un archivo de texto.
Segunda linea.

Esta es una nueva linea añadida

In [37]:
from google.colab import files
files.download("archivo.txt")

In [38]:
from google.colab import drive
uploaded = files.upload()

Saving archivo.txt to archivo (1).txt

In [39]:
with open("archivo.txt", "r") as f:
  print(f. read())

Hola, este es un archivo de texto.
Segunda linea.

Esta es una nueva linea añadida

In [40]:
with open("archivo.txt", "w") as f:
  f.write("este archivo fue completamente modificado\n")
  f.write("Nueva línea 1\n")
  f.write("Nueva linea 2\n")

In [44]:
with open("archivo.txt", "r") as f:
  print(f.read())

este archivo fue completamente modificado
Nueva línea 1
Nueva linea 2

In [46]:
from google.colab import files
files.download("archivo.txt")

Con archivos.csv

In [50]:
import csv

datos = [
    ["Nombre", "Edad", "Ciudad"],
    ["Ana", 25, "Bogotá"],
    ["Luis", 30, "Medellín"],
    ["Carlos", 28, "Cali"]
]

with open("datos.csv", "w", newline="") as f:
  writer = csv.writer(f)         #La función writer es una función integrada?
  writer.writerows(datos)

In [51]:
with open("datos.csv", "r") as f:
  print(f.read())

Nombre,Edad,Ciudad
Ana,25,Bogotá
Luis,30,Medellín
Carlos,28,Cali

In [52]:
files.download("datos.csv")

In [55]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [58]:
ruta = "/content/drive/MyDrive/datos.csv"
import shutil
shutil.copy("datos.csv", ruta) # "datos.csv": archivo origen (en colab) y

'/content/drive/MyDrive/datos.csv'

In [59]:
with open(ruta, "r") as f:
  print(f.read())

Nombre,Edad,Ciudad
Ana,25,Bogotá
Luis,30,Medellín
Carlos,28,Cali

In [61]:
with open(ruta, "r") as f:
  data = list(csv.reader(f))

# Agregar nueva fila
data.append(["Diego", "28", "Armenia"])
data

[['Nombre', 'Edad', 'Ciudad'],
 ['Ana', '25', 'Bogotá'],
 ['Luis', '30', 'Medellín'],
 ['Carlos', '28', 'Cali'],
 ['Diego', '28', 'Armenia']]

In [62]:
import pandas as pd
data1 = pd.DataFrame(data)
data1

        0     1         2
0  Nombre  Edad    Ciudad
1     Ana    25    Bogotá
2    Luis    30  Medellín
3  Carlos    28      Cali
4   Diego    28   Armenia

descargar base de datos y manejo de librerias y graficar

In [63]:
import csv

ruta = "/content/drive/MyDrive/datos.csv"

# Leer
with open(ruta, "r") as f:
    data = list(csv.reader(f))

# Mostrar antes
print("ANTES:")
print(data)

# Agregar fila
data.append(["Diego", "28", "Armenia"])

# Guardar
with open(ruta, "w", newline="") as f:
    writer = csv.writer(f)
    writer.writerows(data)

# Mostrar después
print("\nDESPUÉS:")
with open(ruta, "r") as f:
    print(f.read())

ANTES:
[['Nombre', 'Edad', 'Ciudad'], ['Ana', '25', 'Bogotá'], ['Luis', '30', 'Medellín'], ['Carlos', '28', 'Cali']]

DESPUÉS:
Nombre,Edad,Ciudad
Ana,25,Bogotá
Luis,30,Medellín
Carlos,28,Cali
Diego,28,Armenia

In [64]:
import os
os.listdir("/content/drive/MyDrive")

['Colab Notebooks',
 'Classroom',
 'ERICK SANTIAGO VILLAMIZAR JAIMES',
 'Villamizar Erick Santiago',
 'Erick Santiago Villamizar Jaimes',
 'subir archivo ',
 'ERICK VILLAMIZAR ',
 'Cultura fisica',
 'Documento sin título (2).gdoc',
 'Documento sin título (1).gdoc',
 'Documento sin título.gdoc',
 'library(haven).gdoc',
 'Plantilla con IA.gdoc',
 'Formalización del concepto de grupo.gdoc',
 'Plantilla con IA 5E - Grupo 3.docx',
 'Tabla de identidad.gdoc',
 'Tabla completa de ventas corregida.gsheet',
 'Datos de Jugadores de Selecciones Nacionales.gsheet',
 'Base de Datos Consolidada de Jugadores.gsheet',
 'Selección Colombia: Datos de Jugadores.gsheet',
 'Consolidación de Datos de Jugadores.gsheet',
 'Base de Datos de Jugadores de Fútbol.gsheet',
 'Jugadores y Mundiales Jugados.gsheet',
 'Datos de Jugadores de Fútbol Completos.gsheet',
 'Base de Datos Jugadores Mundialistas .gsheet',
 'Tabla de Calificaciones en Excel.gsheet',
 'datos.csv']

In [66]:
import pandas as pd
df = pd.read_csv(ruta)
df

   Nombre  Edad    Ciudad
0     Ana    25    Bogotá
1    Luis    30  Medellín
2  Carlos    28      Cali
3   Diego    28   Armenia